import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "@/app/providers";
import { StoreProvider } from "@/app/storeProvider";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
